name: Build
# This workflow is triggered on pushes to the repository.
on: push

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{matrix.config.name}}
    runs-on: ${{matrix.config.os}}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
          name: "Ubuntu GCC", artifact: "riesling-linux.tar.gz",
          os: ubuntu-16.04,
          cc: "gcc-9", cxx: "g++-9"
        }
        - {
          name: "macOS", artifact: "riesling-macos.tar.gz",
          os: macos-10.15,
          cc: "clang", cxx: "clang++"
        }

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install GNU tar
        shell: bash
        run: |
          if [ "${{runner.os}}" == "macOS" ]; then
            brew install gnu-tar
          fi

      - name: Build
        shell: bash
        env:
          CC: ${{matrix.config.cc}}
          CXX: ${{matrix.config.cxx}}
        run: |
          cmake/vcpkg/bootstrap-vcpkg.sh
          cmake -B ${{github.workspace}}/build -S ${{github.workspace}} \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/cmake/Plain.cmake
          cmake --build ${{github.workspace}}/build

      # - name: Tests
      #   shell: bash
      #   run: |
      #     ${{github.workspace}}/build/prufung

      - name: Save release
        run: |
          mv ./build/riesling ./
          ALL="riesling"
          if [ "${{runner.os}}" == "macOS" ]; then
            echo "Using GNU tar"
            gtar -cvzf ${{matrix.config.artifact}} $ALL
          else
            echo "Using system tar"
            tar -cvzf ${{matrix.config.artifact}} $ALL
          fi
        shell: bash

      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          path: ./${{matrix.config.artifact}}
          name: ${{matrix.config.artifact}}

  release:
    if: contains(github.ref, 'tags/v')
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        tag_name: ${{github.ref}}
        release_name: Release ${{github.ref}}
        draft: true
        prerelease: false
    
    - name: Store Release URL
      run: |
        echo "${{steps.create_release.outputs.upload_url}}" > ./upload_url
    
    - uses: actions/upload-artifact@v1
      with:
        path: ./upload_url
        name: upload_url
  
  publish:
    if: contains(github.ref, 'tags/v')
    name: ${{matrix.config.name}}
    runs-on: ${{matrix.config.os}}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
          name: "Ubuntu GCC", artifact: "riesling-linux.tar.gz",
          os: ubuntu-16.04
        }
        - {
          name: "macOS", artifact: "riesling-macos.tar.gz",
          os: macos-10.15
        }
    needs: release

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v1
      with:
        name: ${{matrix.config.artifact}}
        path: ./

    - name: Download URL
      uses: actions/download-artifact@v1
      with:
        name: upload_url
        path: ./
    
    - name: Set Upload URL
      id: set_upload_url
      run: |
        URL=`cat ./upload_url`
        echo ${URL}
        echo "::set-output name=upload_url::${URL}"

    - name: Upload to Release
      id: upload_to_release
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.set_upload_url.outputs.upload_url }}
        asset_path: ./${{ matrix.config.artifact }}
        asset_name: ${{ matrix.config.artifact }}
        asset_content_type: application/gzip
